# Do not modify this file!  It was generated by ‘nixos-generate-config’ and may
# be overwritten by future invocations. Please make changes to
# /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = ["${modulesPath}/installer/scan/not-detected.nix"];

  boot = {
    extraModulePackages = [];

    initrd = {
      availableKernelModules = [
        "ahci"
        "ehci_pci"
        "sd_mod"
        "sdhci_pci"
        "usb_storage"
      ];

      kernelModules = [];
    };

    kernelModules = ["kvm-intel"];
  };

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
